### ISSUE TITLE
Use cache for github app installations

### ISSUE THREAD

**Issue by sqin2019** [abcxyz/team-link#27]
see https://github.com/abcxyz/pasture/blob/main/pkg/code/github/code.go#L182 instead of https://github.com/abcxyz/team-link/blob/main/pkg/github/synchronizer.go#L75

**Comment by sethvargo** [comment]
I wonder if the githubauth package should actually do this?

**Comment by sqin2019** [comment]
> I wonder if the githubauth package should actually do this?

Agree since it is reusable, also cc @yolocs.

**Comment by sqin2019** [comment]
Please let me know if I should draft a PR for it in pkg, thanks!

**Comment by sethvargo** [comment]
https://github.com/abcxyz/pkg/pull/334

**Comment by sethvargo** [comment]
@sqin2019 you'll need to update the dependency version of pkg to pick this up.

**Comment by sqin2019** [comment]
> [@sqin2019](https://github.com/sqin2019) you'll need to update the dependency version of pkg to pick this up.

Yep, version is updated - https://github.com/abcxyz/team-link/blob/main/go.mod#L6, https://github.com/abcxyz/pkg/releases/tag/v1.1.1
